
from os.path import join
from os import listdir
import os
import re


from snakemake.remote.S3 import RemoteProvider as S3RemoteProvider
S3 = S3RemoteProvider()

       S3.remote(expand("ccr-genomics-testdata/testdata/Test1_R_T_R{letter}.fastq.gz", letter=["1", "2",]))



samples = [f for f in os.listdir(config['fastqpath']) if re.search('_R1.fastq.gz', f)]
samples = [re.sub("_R1.fastq.gz", "", x) for x in samples]
print(samples)



workpath="./"
#fastqdir=config['fastqpath']

rule all:
	input:
		expand(join(workpath,"{sample}","fastqc","{sample}_R1_fastqc.zip"),sample=samples),	
		expand(join(workpath,"{name}","star_out","{name}.star.bam"),name=samples),
		expand(join(workpath,"{name}","rsem_out","{name}.genes.results"),name=samples),
		expand(join(workpath,"{name}","multiqc","multiqc_report.html"),name=samples)
##
include: join("workflow","rules","qc.smk")
include: join("workflow","rules","count.smk")
