
from os.path import join
from os import listdir
import os
import re


from snakemake.remote.S3 import RemoteProvider as S3RemoteProvider
S3 = S3RemoteProvider()

SAMPLES = ["Test1_R_T"]

workpath="./"


rule all:
	input:
		expand(join(workpath,"{sample}","fastqc","{sample}_R1_fastqc.zip"),sample=samples),	


rule fastqc:
	input:
		R1 = S3.remote("ccr-genomics-testdata/testdata/{sample}_R1.fastq.gz",sample=SAMPLES),
		R2 = S3.remote("ccr-genomics-testdata/testdata/{sample}_R2.fastq.gz",sample=SAMPLES),
	params:
		out = join(workpath,"{name}","fastqc")
	output:
		join(workpath,"{name}","fastqc","{name}_R1_fastqc.zip"),
		join(workpath,"{name}","fastqc","{name}_R2_fastqc.zip")

	envmodules:
	"fastqc/0.11.9"

	container: "docker://nciccbr/ccbr_fastqc_0.11.9:v1.1"
		
	shell: """

	fastqc {input} -o  {params.out}

	"""